#reference filters get applied to the map and to the icp
referenceDataPointsFilters:
#  - MaxDistDataPointsFilter:
#      maxDist: 20.0
  - RandomSamplingDataPointsFilter:
      prob: 1.0
  - SurfaceNormalDataPointsFilter:
      knn: 5
      epsilon: 0
      keepNormals: 1
      keepDensities: 1
  - ObservationDirectionDataPointsFilter
  - OrientNormalsDataPointsFilter 
matcher:
  KDTreeMatcher:
    knn: 3
    maxDist: 10.0
    epsilon: 1.0

outlierFilters:
  - TrimmedDistOutlierFilter:
     ratio: 0.8
  - SurfaceNormalOutlierFilter:
     maxAngle: 1.57

errorMinimizer:
  PointToPlaneErrorMinimizer

transformationCheckers:
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 2
  - CounterTransformationChecker:
      maxIterationCount: 40
  - BoundTransformationChecker:
      maxRotationNorm: 0.8
      maxTranslationNorm: 30.00

inspector:
#  VTKFileInspector
  NullInspector

logger:
#  FileLogger
  NullLogger
