# these filters get applied to the scans from the range sensor every time a scan is received
- DistanceLimitDataPointsFilter:
    dim: -1 # -1 means radial distance, 0 is x, 1 is y, 2 is z
    dist: 50
    removeInside: 0
- DistanceLimitDataPointsFilter:
    dim: 2 # -1 means radial distance, 0 is x, 1 is y, 2 is z
    dist: 2
    removeInside: 0
- DistanceLimitDataPointsFilter:
    dim: 2 # -1 means radial distance, 0 is x, 1 is y, 2 is z
    dist: -0.5
    removeInside: 1
- RandomSamplingDataPointsFilter:
    prob: 0.9
- SurfaceNormalDataPointsFilter:
    knn: 5
    epsilon: 0
    keepNormals: 1
    keepDensities: 1
- ObservationDirectionDataPointsFilter
- OrientNormalsDataPointsFilter 
- MaxDensityDataPointsFilter:
    maxDensity: 10000.0
