icp_localization:
  initial_pose:
    x: 0.0 
    y: -1.0 
    z: 0.0 
    roll: 2.0  
    pitch: 0.0
    yaw: 0.0 
  imu_data_topic: "/imu/data"
  odometry_data_topic: "/odometry/filtered" 
  num_accumulated_range_data: 1
  range_data_topic: "/velodyne_points" 
  is_use_odometry: true
  is_provide_odom_frame: false
  gravity_vector_filter_time_constant: 0.001
  fixed_frame: "map"
  min_num_odom_msgs_before_ready: 1

calibration:
  imu_to_range_sensor:
    x: -0.041
    y: 0.034
    z: -0.057
    roll: 0
    pitch: 0.0
    yaw: 0
  odometry_source_to_range_sensor:
    x: -0.076
    y: -0.024
    z: 0.034
    roll: 0.0
    pitch: 0.0
    yaw: 0.0 
